apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: docker.io/maelhadyf:${BUILD_NUMBER}
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: java-app-route
  labels:
    app: java-app
spec:
  to:
    kind: Service
    name: java-app-service
  port:
    targetPort: 8081
  tls:
    termination: edge
